server:
  port: 3344
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:gaoyh961102/springcloud-config.git
          search-paths:
            - spring-config
      label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-server3344
    prefer-ip-address: true # 访问路径可以显示ip